# Configurações do MongoDB
[mongodb]
uri = "${MONGODB_URI}"  # Será substituído pela variável de ambiente
database = "sbsender"

# Configurações da Aplicação
[app]
debug = false

# Provedor Whatsapp
[provider]
webhook_url = "${PROVIDER_WEBHOOK_URL}"  # Será substituído pela variável de ambiente

# streamlit
STREAMLIT_PRODUCTION = true