# Este arquivo serve como template para as configurações
# As credenciais reais devem ser configuradas no Streamlit Cloud

[mongodb]
uri = "" # Configure no Streamlit Cloud
database = "sbsender"

[app]
debug = false

[provider]
webhook_url = "" # Configure no Streamlit Cloud

# streamlit
STREAMLIT_PRODUCTION = true