# Configurações do MongoDB
[mongodb]
uri = "mongodb://ukRBNY0uVg:pjXhQ2exfVz86d@transbyshop.ddns.net:27977/?retryWrites=true&connectTimeoutMS=10000&authSource=admin&authMechanism=SCRAM-SHA-1&serverSelectionTimeoutMS=5000"  # Será substituído pela variável de ambiente
database = "sbsender"

# Configurações da Aplicação
[app]
debug = false

# Provedor Whatsapp
[provider]
webhook_url = "https://n8nwebhooks.i92tecn.com.br"  # Será substituído pela variável de ambiente

# streamlit
STREAMLIT_PRODUCTION = true