# Configurações do MongoDB
MONGODB_URI = teste
MONGODB_DATABASE = sbsender

# Configurações da Aplicação
DEBUG = false


# Provedor Whatsapp
PROVIDER_WEBHOOK_URL = teste

# streamlit
STREAMLIT_PRODUCTION = true